services:
  app:
    build: .
    ports:
      - "8000:9000"
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "app:9000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040