name: Build and deploy a client to an Azure Web App

env:
  AZURE_WEBAPP_NAME: ebiznes-frontend-lab

on:
  push:
    paths:
      - 'task-5/client/**'

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup tests
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: task-5/client/package-lock.json

      - run: npm ci
        working-directory: task-5/client

      - name: Run tests
        run: npm test
        working-directory: task-5/client

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./task-5/client
          tags: ghcr.io/${{ env.REPO }}/client:${{ github.sha }}
          file: task-5/client/Dockerfile

  notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build client - ${{ github.repository }}
          body: Build status - ${{ needs.build.result }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_NAME }}
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_CLIENT_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}/client:${{ github.sha }}'
